<a href="https://colab.research.google.com/github/MargaritaFateeva/PythonSeminars/blob/main/dz10_task44.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# | Задание 44 |
# | --- |
# | В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

# import random
# lst = ['robot'] * 10
# lst += ['human'] * 10
# random.shuffle(lst)
# data = pd.DataFrame({'whoAmI'lst})
# data.head() |

In [1]:
import pandas as pd

In [6]:
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  robot
1  human
2  robot
3  human
4  robot

In [12]:
data.loc[data['whoAmI']=='robot', 'robot']=1
data.loc[data['whoAmI']!='robot', 'robot']=0
data.loc[data['whoAmI']=='human', 'human']=1
data.loc[data['whoAmI']!='human', 'human']=0
data_res=data[['human', 'robot']]
data_res.head()

   human  robot
0    0.0    1.0
1    1.0    0.0
2    0.0    1.0
3    1.0    0.0
4    0.0    1.0

In [9]:
data_1=pd.get_dummies(data['whoAmI'])
data_1.head()

   human  robot
0      0      1
1      1      0
2      0      1
3      1      0
4      0      1